version: 2
jobs:
  build:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              sudo apt-get update
              sudo apt-get -y install wget zip unzip bzip2
      - run:
          name: Download Godot 3.2.2
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_linux_headless.64.zip
              unzip Godot_v3.2.2-stable_linux_headless.64.zip
              mv Godot_v3.2.2-stable_linux_headless.64 godot
              chmod +x godot
      - run:
          name: Download Godot 3.2.2 Export Templates
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_export_templates.tpz
              mkdir -p ~/.local/share/godot/templates
              unzip Godot_v3.2.2-stable_export_templates.tpz -d ~/.local/share/godot/templates
              mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/3.2.2.stable
      - run:
          name: Export win64 build
          command: |
              mkdir win64
              ./godot --path project.godot --export win64 "win64/Mazerator.exe"
              zip win64.zip win64/*
      - run:
          name: Export linux64 build
          command: |
              mkdir linux64
              ./godot --export linux64 --path project.godot "linux64/Mazerator"
              zip linux64.zip linux64/*

      - run:
          name: Export mac build
          command: |
              ./godot --export macos --path project.godot "Mazerator-mac"
              mv Mazerator-mac Mazerator-mac.zip
      - run:
          name: Export win32 build
          command: |
              mkdir win32
              ./godot --export win32 --path project.godot "win32/Mazerator.exe"
              zip win32.zip win32/*
      - run:
          name: Export linux32 build
          command: |
              mkdir linux32
              ./godot --export linux32 --path project.godot "linux32/Mazerator"
              zip linux32.zip linux32/*
      - run:
          name: Upload to GitHub
          command: |
              wget https://github.com/github-release/github-release/releases/download/v0.8.1/linux-amd64-github-release.bz2
              bzip2 -d linux-amd64-github-release.bz2
              cd linux-amd64-github-release
              export GITHUB_TOKEN=${GITHUB_TOKEN}
              github-release release \
                --user MazeratorBot \
                --repo ${CIRCLE_PROJECT_REPONAME} \
                --tag ${CIRCLE_SHA1} \
                --name ${CIRCLE_SHA1} \
                --description "An automated upload from our CI" \
                --pre-release
              github-release upload \
                --user MazeratorBot \
                --repo ${CIRCLE_PROJECT_REPONAME} \
                --tag ${CIRCLE_SHA1} \
                --name ${CIRCLE_SHA1} \
                --file ../github/.                
              
      - store_artifacts:
           path: win64.zip
           destination: win64.zip
        
      - store_artifacts:
           path: win32.zip
           destination: win32.zip
        
      - store_artifacts:
           path: linux64.zip
           destination: linux64.zip
        
      - store_artifacts:
           path: linux32.zip
           destination: linux32.zip
        
      - store_artifacts:
           path: Mazerator-mac.zip
           destination: Mazerator-mac.zip